# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bebbf857a04a5da9775a2cc4f2e2b322c7d5f52d3ca51ecaac08fb73936a11ce5c8191fb6e94374be30c50a029e10a967655e8f6faa110e0525ecf460d28e334

test:
  secret_key_base: c68c05eb0bbd7d03658477b937812f18816438d815a37e074ddd67eddbdc09f2cfda9aa161df2bbb3d501f15243c0d016e6ddf6ab89209a78424c91be198b280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
